
export const SUBMIT_LOGING_REQUEST = "SUBMIT_LOGING_REQUEST";
export const SUBMIT_LOGING_SUCCESS = "SUBMIT_LOGING_SUCCESS";
export const SUBMIT_LOGING_FAILURE = "SUBMIT_LOGING_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const GET_PLAYERS_REQUEST = "GET_PLAYERS_REQUEST";
export const GET_PLAYERS_SUCCESS = "GET_PLAYERS_SUCCESS";
export const GET_PLAYERS_FAILURE = "GET_PLAYERS_FAILURE";


