
export const SUBMIT_LOGING = "SUBMIT_LOGING";
export const LOGOUT = "LOGOUT";

export const GET_PLAYERS_REQUEST = "GET_PLAYERS_REQUEST";
export const GET_PLAYERS_SUCCESS = "GET_PLAYERS_SUCCESS";
export const GET_PLAYERS_FAILURE = "GET_PLAYERS_FAILURE";

export const CHECK_CARD = "CHECK_CARD";
export const PUSH_CARDS = "PUSH_CARDS";
export const SAVE_PROFILE = "SAVE_PROFILE";

