
export const SUBMIT_LOGING = "SUBMIT_LOGING";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const GET_PLAYERS_REQUEST = "GET_PLAYERS_REQUEST";
export const GET_PLAYERS_SUCCESS = "GET_PLAYERS_SUCCESS";
export const GET_PLAYERS_FAILURE = "GET_PLAYERS_FAILURE";

export const CHECK_CARD = "CHECK_CARD";

export const PUSH_CARDS_REQUEST = "PUSH_CARDS_REQUEST";
export const PUSH_CARDS_SUCCESS = "PUSH_CARDS_SUCCESS";
export const PUSH_CARDS_FAILURE = "PUSH_CARDS_FAILURE";

export const SAVE_PROFILE_REQUEST = "SAVE_PROFILE_REQUEST";
export const SAVE_PROFILE_SUCCESS = "SAVE_PROFILE_SUCCESS";
export const SAVE_PROFILE_FAILURE = "SAVE_PROFILE_FAILURE";


